name: Codsalah
title: Data Engineering & Scalable Solutions
description: >-
  Professional insights into Data Engineering, Big Data architectures, and the development of resilient ETL pipelines.
lang: en-US
timezone: Africa/Cairo
data-theme: dark

author:
  name: Codsalah
  bio: Data Engineer | Computer Engineering Student | Big Data Enthusiast
  userpicture:
  username: codsalah
  github: codsalah
  twitter: SalahAlgamasy
  linkedin: salah-algamasy

url: "https://codsalah.github.io"
baseurl: ""
canonical_url: true

social:
  name: Codsalah
  links:
    - https://x.com/SalahAlgamasy
    - https://www.linkedin.com/in/salah-algamasy/
    - https://github.com/codsalah

library_tags:
  - introduction
  - data-engineering
  - big-data
  - spark
  - sql
  - batch-processing
  - python
  - automation
  - devops
  - docker
  - software-engineering
  - mathematics
  - oop
  - security

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

include:
  - assets

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
